### ISSUE TITLE
Admin-Permission Pages Error in 2.1.0-stable

### ISSUE THREAD

**Issue by ryanemax** [taigaio/taiga-front#1074]
When I enter Permission Pages it happens, that I can't edit any permissions in user_role tables.
``` js
angular.js:12477 TypeError: Array.prototype.indexOf called on null or undefined
    at indexOf (native)
    at http://taiga.anasit.com/v-1463480691365/js/app.js:11:9968
    at c (http://taiga.anasit.com/v-1463480691365/js/libs.js:5:29139)
    at Function.jo [as map] (http://taiga.anasit.com/v-1463480691365/js/libs.js:6:25238)
    at o (http://taiga.anasit.com/v-1463480691365/js/app.js:11:9904)
    at d (http://taiga.anasit.com/v-1463480691365/js/app.js:11:10704)
    at m (http://taiga.anasit.com/v-1463480691365/js/app.js:11:12747)
    at Object.fn (http://taiga.anasit.com/v-1463480691365/js/app.js:1:15587)
    at p.$digest (http://taiga.anasit.com/v-1463480691365/js/libs.js:10:10682)
    at p.$apply (http://taiga.anasit.com/v-1463480691365/js/libs.js:10:12256)
    at http://taiga.anasit.com/v-1463480691365/js/libs.js:10:8382
    at i (http://taiga.anasit.com/v-1463480691365/js/libs.js:8:27498)
    at http://taiga.anasit.com/v-1463480691365/js/libs.js:8:28952
```

Only the External User's permissions cloud change.

btw, there is no error in taiga-back logs.

- taiga-back-2.1.0
- taiga-front-dist-2.1.0-stable

**Comment by superalex** [comment]
Hello @ryanemax 

I could reproduce your issue if using taiga-back in master branch and taiga-front in stable, could you please check you are using the stable branch in taiga-back?

Regards,

**Comment by ryanemax** [comment]
thanks, it's work, when I
``` sh
cd taiga-back
git checkout stable
git pull
```
