### ISSUE TITLE
cannot edit role permissions

### ISSUE THREAD

**Issue by jonbayer** [taigaio/taiga-front#1090]
Hi,

When I attempt to edit permissions on the project page I get an error such as:
libs.js:11 TypeError: Array.prototype.indexOf called on null or undefined
    at indexOf (native)
    at https://taiga.cpkn.ca/v-1470787831650/js/app.js:11:11166
    at f (https://taiga.cpkn.ca/v-1470787831650/js/libs.js:6:5880)
    at Function.ma [as map] (https://taiga.cpkn.ca/v-1470787831650/js/libs.js:7:4931)
    at o (https://taiga.cpkn.ca/v-1470787831650/js/app.js:11:11102)
    at f (https://taiga.cpkn.ca/v-1470787831650/js/app.js:11:11898)
    at g (https://taiga.cpkn.ca/v-1470787831650/js/app.js:11:14200)
    at https://taiga.cpkn.ca/v-1470787831650/js/app.js:1:15947
    at d.$digest (https://taiga.cpkn.ca/v-1470787831650/js/libs.js:11:15640)
    at d.$apply (https://taiga.cpkn.ca/v-1470787831650/js/libs.js:11:17131)
    at HTMLAnchorElement.<anonymous> (https://taiga.cpkn.ca/v-1470787831650/js/libs.js:13:21027)
    at HTMLAnchorElement.dispatch (https://taiga.cpkn.ca/v-1470787831650/js/libs.js:4:31709)
    at HTMLAnchorElement.m.handle (https://taiga.cpkn.ca/v-1470787831650/js/libs.js:4:29784)(anonymous function) @ libs.js:11

I'm running the latest master branch, is there something I have done wrong or is this a known issue?

**Comment by Xaviju** [comment]
What browser and version are you using?
Can you explain the steps to reproduce it?

**Comment by jonbayer** [comment]
running the latest master branch, can reproduce in firefox, chrome. to reproduce go to project admin, then permissions. attempt to create a role and then set permissions on this. I'm using taiga-event as well; if that plays a role

**Comment by bameda** [comment]
The master branch is unstable. Use always the stable branch.

**Comment by jonbayer** [comment]
https://github.com/taigaio/taiga-back/commit/c414e6b9c4998bd5fb9f15343a2a3b278fadb096

that fixed it, thanks.

**Comment by bameda** [comment]
Yes, but master branch is very unstable and you can lose information. Please only use master branch for test or dev purpose.
