### ISSUE TITLE
taiga-events stop working

### ISSUE THREAD

**Issue by apoks** [taigaio/taiga-front#1237]
**What is the current behavior?**
After starting taiga-events ist stops automatically after some second. If i start it again with `circusctl start taiga-events` ist stops again after some seconds. Here is the taigaevents.stderr.log:

`TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/home/taiga/taiga-events/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/taiga/taiga-events/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/taiga/taiga-events/node_modules/ws/index.js:9:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/taiga/taiga-events/index.coffee:4:19)
    at Object.<anonymous> (/home/taiga/taiga-events/index.coffee:1:1)
    at Module._compile (module.js:410:26)
    at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:173:23)
    at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
    at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
    at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3`

**Is it happening in taiga.io or in your own instance?**
Own instance

**What browser/version are you using?**
Newest version

Thanks for reporting!

**Comment by bameda** [comment]
This is like https://github.com/taigaio/taiga-events/issues/24

You are using an old version of node, please upgrade node to a version >= 6.0 (The current stable is 7.7.0 and the last LTS is 6.10.0 LTS).

**Comment by apoks** [comment]
Hey bameda,

thx for the quick reply. I updated node now to 7.6.0. Now taiga-events runs fine.

But in the Chrome console i get much errors.
`WebSocket connection to 'wss://xxxxxxxxxx.xxx:8888/events' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED`

Just followed the howto http://taigaio.github.io/taiga-doc/dist/setup-production.html to install taiga with https.

**Comment by bameda** [comment]
You are welcome.
Are you sure that taiga-events is running in  `xxxxxxxxxx.xxx:8888/events`?
Could it be a problem with your nginx configuration? maybe the proxy pass

**Comment by apoks** [comment]
If u do `circusctl status` i get the following output:

`circusd-stats: active
plugin:flapping: active
taiga: active
taiga-celery: active
taiga-events: active`

Here is the part of the nginx vhost:

`server {
    listen 9996 default_server;
    server_name xxxxxxxxxx.xxx;
    return 301 https://$server_name$request_uri;
}

server {
    listen 9997 ssl default_server;
    server_name xxxxxxxxxx.xxx;

    large_client_header_buffers 4 32k;
    client_max_body_size 50M;
    charset utf-8;

    index index.html;

    # Frontend
    location / {
        root /home/taiga/taiga-front-dist/dist/;
        try_files $uri $uri/ /index.html;
    }

    # Backend
    location /api {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8001/api;
        proxy_redirect off;
    }

    location /admin {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8001$request_uri;
        proxy_redirect off;
    }

    # Static files
    location /static {
        alias /home/taiga/taiga-back/static;
    }

    # Media files
    location /media {
        alias /home/taiga/taiga-back/media;
    }

    # Events
    location /events {
       proxy_pass http://127.0.0.1:8888/events;
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       proxy_connect_timeout 7d;
       proxy_send_timeout 7d;
       proxy_read_timeout 7d;
    }`

**Comment by bameda** [comment]
Try to configure taiga-front to rub with `wss://xxxxxxxxxx.xxx/events` instead of `wss://xxxxxxxxxx.xxx:8888/events` because you are doing a proxy pass according to nginx

**Comment by apoks** [comment]
Yep now it works. No errors anymore. Thx for the fast support !

**Comment by bameda** [comment]
Great!! :smiley_cat: 

You are welcome.
