### ISSUE TITLE
Taiga frontend crashed suddenly!

### ISSUE THREAD

**Issue by uhlhosting** [taigaio/taiga-front#1600]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
Bug/Issue
**What is the current behavior?**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6324047/47082718-dc2b4b00-d20e-11e8-906d-4cbaed05f2db.png">

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/6324047/47083757-e1d66000-d211-11e8-8701-5fcc2dc45939.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6324047/47083800-0b8f8700-d212-11e8-8629-61d3f59f0346.png">

**If the current behavior is a bug, please provide the steps to reproduce.**
```
taiga@ipm:~$ cd ~/taiga-back
taiga@ipm:~/taiga-back$ workon taiga
(taiga) taiga@ipm:~/taiga-back$ python manage.py loaddata initial_project_templates --traceback
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/taiga/taiga-back/settings/__init__.py", line 26, in <module>
    from .local import *
  File "/home/taiga/taiga-back/settings/local.py", line 1, in <module>
    from .common import *
  File "/home/taiga/taiga-back/settings/common.py", line 544
    GITLAB_VALID_ORIGIN_IPS = ["92.222.242.249"]]
                                                ^
SyntaxError: invalid syntax
(taiga) taiga@ipm:~/taiga-back$ 
```

**What is the expected behavior?**
We just run into the website and all the images and text were gone.

**Is it happening in taiga.io or in your own instance?**
Own instance.
**What browser/version are you using?**
Safari/Chrome latest versions
**Are there any console errors *(Ctrl + F12)* in red?**

```
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (projects, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (projects, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (epics, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (tasks, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (userstories, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (epics, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (userstories, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (issues, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (tasks, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (issues, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (joyride, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (user-storage, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (joyride, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (joyride, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (joyride, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (stats, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (16, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (projects, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (userstories, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (tasks, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (issues, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (issues, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (tasks, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (userstories, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (epics, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (epics, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (joyride, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (discover, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (projects, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (projects, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (projects, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (joyride, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (stats, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (16, line 0)
> Selected Element
< <div ng-if="!vm.timelineList.size">…</div>
```

Thanks for reporting!

**Comment by alexhermida** [comment]
@uhlhosting you have an error in the backend, as you can check in the traceback there is a syntax error:
```diff
-GITLAB_VALID_ORIGIN_IPS = ["92.222.242.249"]]
+GITLAB_VALID_ORIGIN_IPS = ["92.222.242.249"]
```
probably because of that the frontend it's not loading properly.

**Comment by uhlhosting** [comment]
> @uhlhosting you have an error in the backend, as you can check in the traceback there is a syntax error:
> 
> ```diff
> -GITLAB_VALID_ORIGIN_IPS = ["92.222.242.249"]]
> +GITLAB_VALID_ORIGIN_IPS = ["92.222.242.249"]
> ```
> 
> probably because of that the frontend it's not loading properly.

I had that fixed, noticed after post, is not that.

**Comment by uhlhosting** [comment]
> Ok. The backend is given you a 502 status code. Make sure your taiga-front is requesting to the correct backend and check the backend config https://taigaio.github.io/taiga-doc/dist/setup-production.html#_frontend_installation. Probably you have some misconfiguration at taiga-back

This is nothing to do with that line, Like I mentioned above, the issue is not resolved, and evolves around the UPPERCASE letters, and now there are not such 502 errors, they were due to upgrade, replacing common.py where I had lot of config done.

**Comment by uhlhosting** [comment]
@alexhermida I have also replied here including errors, isn't someone able to help us? Not even paid... I mean we need help, this is not a miss-configuration as it is a bug, and it seems in my attempt to fix it, i ruined more...

**Comment by uhlhosting** [comment]
@alexhermida I have updated with a wetransfer file the tickets in taiga.io . Its a bit weird too many were opened only for this one issue.
