### ISSUE TITLE
taiga-front doesn't seem to compile with node v12

### ISSUE THREAD

**Issue by jwir3** [taigaio/taiga-front#1756]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When using node v12+, the following error occurs during compilation: 
```
In file included from ../src/binding.cpp:1:0:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
  g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/scottj/.node-gyp/12.3.1/include/node -I/home/scottj/.node-gyp/12.3.1/src -I/home/scottj/.node-gyp/12.3.1/deps/openssl/config -I/home/scottj/.node-gyp/12.3.1/deps/openssl/openssl/include -I/home/scottj/.node-gyp/12.3.1/deps/uv/include -I/home/scottj/.node-gyp/12.3.1/deps/zlib -I/home/scottj/.node-gyp/12.3.1/deps/v8/include -I../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/create_string.o.d.raw   -c -o Release/obj.target/binding/src/create_string.o ../src/create_string.cpp
../src/create_string.cpp: In function ‘char* create_string(Nan::MaybeLocal<v8::Value>)’:
../src/create_string.cpp:17:37: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>&)’
   v8::String::Utf8Value string(value);
                                     ^
In file included from /home/scottj/.node-gyp/12.3.1/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/create_string.cpp:1:
/home/scottj/.node-gyp/12.3.1/include/node/v8.h:2995:5: note: candidate: v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)
     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
     ^~~~~~~~~
/home/scottj/.node-gyp/12.3.1/include/node/v8.h:2995:5: note:   candidate expects 2 arguments, 1 provided
binding.target.mk:122: recipe for target 'Release/obj.target/binding/src/create_string.o' failed
make: *** [Release/obj.target/binding/src/create_string.o] Error 1
make: Leaving directory '/home/taiga/Source/taiga/taiga-front/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/taiga/Source/taiga/taiga-front/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-45-generic
gyp ERR! command "/home/scottj/.nvm/versions/node/v12.3.1/bin/node" "/home/taiga/Source/taiga/taiga-front/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/taiga/Source/taiga/taiga-front/node_modules/node-sass
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed
npm WARN The package bluebird is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.7.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.7.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/scottj/.npm/_logs/2019-05-24T21_46_21_627Z-debug.log
```

I have attached the above log here: [2019-05-24T21_46_21_627Z-debug.log](https://github.com/taigaio/taiga-front/files/3218692/2019-05-24T21_46_21_627Z-debug.log)

In addition, when attempting run `gulp scss-lint`, I get the following exception:
```
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/home/taiga/Source/taiga/taiga-front/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/taiga/Source/taiga/taiga-front/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/taiga/Source/taiga/taiga-front/node_modules/gulp/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
```

I suspect these are related, as they seem to both have to do with old versions of packages being used in `package.json`.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install `nvm` to switch node versions.
2. `nvm install node`
```
Now using node v12.3.1 (npm v6.9.0)
```
3. `nvm use node`
4. `rm -rf node_modules`
5. `npm install`

**What is the expected behavior?**
No errors. If I switch to node v8.9.3, the errors no longer occur.

**Is it happening in taiga.io or in your own instance?**
My own instance setup for development on Ubuntu Linux 18.04.

**What browser/version are you using?**
N/A

**Are there any console errors *(Ctrl + F12)* in red?**

Thanks for reporting!

**Comment by alexhermida** [comment]
@jwir3 yes, we have an open branch to update all dependencies and make it also compatible with latest node versions. Meanwhile, if you don't have changes in the code, you could use the compiled version of the front: https://github.com/taigaio/taiga-front-dist
