### ISSUE TITLE
Cannot compile newly installed frontend

### ISSUE THREAD

**Issue by Fuzzipede** [taigaio/taiga-front#1774]
**Do you want to request a *feature* or report a *bug*?**
bug 
**What is the current behavior?**
Try to setup a development environment for taiga front on Ubuntu 16.04.
I tried it with a server and tried it with a WLS (windows linux subsystem).

Everything works until I run gulp.

I get the error:
/home/nwa/taiga-front/node_modules/gulp-order/lib/index.js:7
  ({Minimatch} = require("minimatch"));
   ^

ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/nwa/taiga-front/gulpfile.js:26:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at execute (/usr/local/lib/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:28:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/node_modules/gulp-cli/index.js:201:24)

**If the current behavior is a bug, please provide the steps to reproduce.**
Follow the setup  instruction for Taiga-Frontend development (https://taigaio.github.io/taiga-doc/dist/setup-development.html)

**What is the expected behavior?**
It should compile.

**Comment by alexhermida** [comment]
@Fuzzipede which version of `node` are you using? Nevertheless, if you didn't make any modification, you can use the compiled version of [taiga-front](https://github.com/taigaio/taiga-front-dist)
