### ISSUE TITLE
Unable to post comments and description with special chars like "üö..."

### ISSUE THREAD

**Issue by nomorebugs** [taigaio/taiga-front#692]
At our local Taiga installation it is sometimes impossible to post comments or task descriptions with special characters. Never the less they appear in the timeline. A workaround is to recreate a task. There must be something wrong with creating new tasks. The error seems like random, but maybe it is related to creating tasks in a particular way or editing/moving them. The error returned when creating tasks with special chars is a 500.

**Comment by nomorebugs** [comment]
Update: This happens every time a particular user is assigned to a task. Furthermore adding new users to projects is impossible now because of 500 error. Restarting taiga and nginx doesn't help. No problems with other webservices or database server.

**Comment by bameda** [comment]
What is the message of this 500 error? Taiga support unicode if your SO and database is configured to support unicode.

**Comment by nomorebugs** [comment]
Error is {"error": "Server application error"}

It cannot be related to unicode support, because posting unicode characters is normally perfectly fine.

**Comment by bameda** [comment]
Enable debug in taiga-back

in taiga-back/settings/local.py
```python
DEBUG = True
```
restart it and try again.

Error message must be more descriptive (with the complete traceback and a better explanation)

**Comment by nomorebugs** [comment]
I turned debugging on and this is what i get in the unicorn log. As i said, it is not a general problem with unicode, but it just happens sometimes.

```
ERROR:2015-10-28 11:31:59,152: Internal Server Error: /api/v1/tasks/10
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 81, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 420, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 417, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 170, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 165, in update
    self.post_save(self.object, created=False)
  File "/home/taiga/taiga-back/taiga/projects/occ/mixins.py", line 83, in post_save
    super().post_save(obj, created)
  File "/home/taiga/taiga-back/taiga/projects/history/mixins.py", line 71, in post_save
    super().post_save(obj, created=created)
  File "/home/taiga/taiga-back/taiga/projects/notifications/mixins.py", line 68, in post_save
    self.send_notifications(obj)
  File "/home/taiga/taiga-back/taiga/projects/notifications/mixins.py", line 65, in send_notifications
    services.send_notifications(obj, history=history)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/projects/notifications/services.py", line 240, in send_notifications
    send_sync_notifications(notification.id)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/projects/notifications/services.py", line 274, in send_sync_notifications
    email.send(user.email, context)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/djmail/template_mail.py", line 125, in send
    return email.send()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/message.py", line 286, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/backends/console.py", line 36, in send_messages
    self.write_message(message)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/backends/console.py", line 23, in write_message
    self.stream.write('%s\n' % msg_data)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 684-687: ordinal not in range(128)
```

**Comment by bameda** [comment]
Try to change the locale of your system. Like in https://github.com/taigaio/taiga-back/issues/298#issuecomment-88475061 in the taiga user ```.bashrc``` file add:

```
export LANG=en_US.UTF-8
export LC_TYPE=en_US.UTF-8
```

Restart the machine and try it again.

**Comment by nomorebugs** [comment]
Thx a lot! It solved the problem. I really appreciate your fast help here. 
Would be a good idea to add this to the installation instructions or make some kind of Troubleshooting FAQ.

**Comment by bameda** [comment]
You are welcome. I'm glad it worked.

Thank you for the advice, It's not an error that always happen but we can add this informatio to the FAQs here https://github.com/taigaio/taiga-doc/blob/master/setup-production.adoc#7-faq

**Comment by bameda** [comment]
@nomorebugs documentation has been updated http://taigaio.github.io/taiga-doc/dist/setup-faqs.html#bug-unicodeencodeerror
