### ISSUE TITLE
Application not working when email is not configured properly

### ISSUE THREAD

**Issue by Klapsa2503** [taigaio/taiga-front#792]
I have found an issue in taiga, the problem is that you cannot manage tasks (edit, move, etc.) when your email account for email notifications is misconfigured. The problem was hard to find as you can do all the stuff such as moving tasks between sprints but after a page reload they are returning to previous positions.

I suggest that you create a system of email notifications stored in database with some scheduler that will be trying to send/resend them in case there will be problem with communication with mail server.

In case there will be an error with email notification you could display message such as: "Mail notofications are not working, contact administrator for more details." in the application.

Stacktrace:
```
ERROR:2015-12-21 12:43:26,096: Internal Server Error: /api/v1/tasks/4
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 81, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 420, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 417, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 170, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/projects/tasks/api.py", line 86, in update
    return super().update(request, *args, **kwargs)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 165, in update
    self.post_save(self.object, created=False)
  File "/home/taiga/taiga-back/taiga/projects/occ/mixins.py", line 83, in post_save
    super().post_save(obj, created)
  File "/home/taiga/taiga-back/taiga/projects/history/mixins.py", line 73, in post_save
    super().post_save(obj, created=created)
  File "/home/taiga/taiga-back/taiga/projects/notifications/mixins.py", line 105, in post_save
    self.send_notifications(obj)
  File "/home/taiga/taiga-back/taiga/projects/notifications/mixins.py", line 102, in send_notifications
    services.send_notifications(obj, history=history)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/taiga/taiga-back/taiga/projects/notifications/services.py", line 235, in send_notifications
    send_sync_notifications(notification.id)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/taiga/taiga-back/taiga/projects/notifications/services.py", line 292, in send_sync_notifications
    email.send(user.email, context, headers=headers)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/djmail/template_mail.py", line 125, in send
    return email.send()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/message.py", line 303, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
    new_conn_created = self.open()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/backends/smtp.py", line 67, in open
    self.connection.login(self.username, self.password)
  File "/usr/lib/python3.4/smtplib.py", line 652, in login
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/answer/14257 200sm19975100wmn.11 - gsmtp')
```

**Comment by superalex** [comment]
Hello!,

Taiga actually includes such system. If Taiga is working in synchronous mode and the email server fails the action trying to send the email will also fail (save, delete...)

You can make Taiga notifications work in asynchronous mode if you set  "CHANGE_NOTIFICATIONS_MIN_INTERVAL" to a value different than 0, this setting assumes you are manually calling the send_notifications command "python manage.py send_notifications" (the easiest way should be doing it from a cron job)

Regards!,
