### ISSUE TITLE
how to create new users ?

### ISSUE THREAD

**Issue by ddonindia** [taigaio/taiga-front#856]
Hi,

I am able to successfully installed ( I think so :) )  taiga on my rpi2 box. I am able to login with admin user and do some basic stuff.
Now the problem is when I try to create new user by clicking signup link i get 404 error.

"Error 404. The page you are looking for no longer exists. Perhaps you can return back to TAIGA homepage and see if you can find what you are looking for."

I also have following error in nginx logs:

```
2016/02/03 23:52:05 [error] 580#0: *164 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.3, server: _, request: "GET /api/v1/projects?order_by=-total_activity_last_week HTTP/1.1", upstream: "http://192.168.2.51:8001/api/v1/projects?order_by=-total_activity_last_week", host: "192.168.2.51", referrer: "http://192.168.2.51/discover"
2016/02/03 23:52:05 [error] 580#0: *167 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.3, server: _, request: "GET /api/v1/projects?is_featured=true HTTP/1.1", upstream: "http://192.168.2.51:8001/api/v1/projects?is_featured=true", host: "192.168.2.51", referrer: "http://192.168.2.51/discover"
```

Looks some problem with config but not sure were.

can you please help

**Comment by superalex** [comment]
Hello  @ddonindia,

What's exactly the url generating that 404?, are you serving Taiga using nginx?.

Regards!,

**Comment by ddonindia** [comment]
When I click on SignUp link on home page.
http://192.168.2.51/not-found?next=%252Fdiscover is error url.
Yes I am using nginx to serve Taiga.

**Comment by superalex** [comment]
When you click on signup link, what's the url you are trying to access? (not the not-found one). Are you using the last stable releases for both taiga-back and taiga-front?

**Comment by superalex** [comment]
Any news bout this?

**Comment by ddonindia** [comment]
Extremely sorry for late reply.
Signup page points to  http://192.168.2.51/discover#
following is from firefox inspect element

<a ng-click="vm.register()" href="#" title="Sign up" class="register">Sign up</a>

**Comment by superalex** [comment]
Could you please check your javascript console to check if the API requests are returning with error?

**Comment by ddonindia** [comment]
When I click signup buton I am not seeing any activity in javascript  console
![error](https://cloud.githubusercontent.com/assets/16450468/13083292/5b7b1724-d4fa-11e5-91cf-a0e493c7c4bc.png)

**Comment by superalex** [comment]
I was expecting to see the network tab just to check where are going the API requests and their status. Something like:

![image](https://cloud.githubusercontent.com/assets/1579633/13102162/1d4cd8fa-d54c-11e5-9a77-d2b479927f1b.png)

**Comment by ddonindia** [comment]
For some reason I got 0 requests.
![error](https://cloud.githubusercontent.com/assets/16450468/13117524/4bae32a0-d5c6-11e5-9826-b25bb10eda0f.png)

**Comment by superalex** [comment]
Could you please try doing it with chrome enabling the "Preserve log" option?

**Comment by ddonindia** [comment]
Attached screenshot using chrome. Still dont see any traffic.
![error](https://cloud.githubusercontent.com/assets/16450468/13258633/efffb77c-da79-11e5-9d0a-c672fe309d8d.png)
btw I am using taiga-front-dist repo.

**Comment by superalex** [comment]
Could you please attach the image with all the network requests?, when accessing to the root url not just to the error page.

**Comment by ddonindia** [comment]
I see following errors when I load front page 
![error](https://cloud.githubusercontent.com/assets/16450468/13266423/10be4b44-da9e-11e5-99a1-f327137f01a5.png)

**Comment by ddonindia** [comment]
![error](https://cloud.githubusercontent.com/assets/16450468/13266594/d228f0ae-da9e-11e5-8be6-72b25a697d12.png)

**Comment by superalex** [comment]
Everything seems to be ok, none of the API calls is giving a 500 erros, could you show us your conf.json file please?

The taiga-events error is not important, it just means it isn't configured in your instance.

**Comment by ddonindia** [comment]
following is conf.json from taiga-front-dist/dist
```
{
    "api": "http://192.168.2.51/api/v1/",
        "eventsUrl": "ws://192.168.2.51/events",
        "debug": "true",
        "publicRegisterEnabled": false,
        "feedbackEnabled": true,
        "privacyPolicyUrl": null,
        "termsOfServiceUrl": null,
        "maxUploadFileSize": null,
        "contribPlugins": []
}
```
I am ruing taiga-back on 8001 port.

**Comment by superalex** [comment]
And can you access http://192.168.2.51/api/v1/ from your browser?

**Comment by bameda** [comment]
taiga-back return a 502.

**Comment by superalex** [comment]
where did you see it @bameda ?

**Comment by bameda** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/877218/13279046/0f178652-dad5-11e5-9a4a-4f2c71c659a4.png)

**Comment by superalex** [comment]
@ddonindia if 502 errors are happening you should check your taiga-back error logs, check the logs folder from your taiga user.

**Comment by ddonindia** [comment]
@bameda I have faced similar error. in my case postgresql service was down.

@superalex  yes I am able to access http://192.168.2.51/api/v1 in browser. 

following is output in browser:

```
{
    "exporter": "http://192.168.2.51/api/v1/exporter",
        "webhooklogs": "http://192.168.2.51/api/v1/webhooklogs",
        "points": "http://192.168.2.51/api/v1/points",
        "gitlab-hook": "http://192.168.2.51/api/v1/gitlab-hook",
        "issues/(?P<resource_id>\\d+)/voters": "http://192.168.2.51/api/v1/issues/(?P<resource_id>\\d+)/voters",
        "timeline/project": "http://192.168.2.51/api/v1/timeline/project",
        "issue-custom-attributes": "http://192.168.2.51/api/v1/issue-custom-attributes",
        "applications": "http://192.168.2.51/api/v1/applications",
        "milestones": "http://192.168.2.51/api/v1/milestones",
        "resolver": "http://192.168.2.51/api/v1/resolver",
        "history/wiki": "http://192.168.2.51/api/v1/history/wiki",
        "userstories/(?P<resource_id>\\d+)/voters": "http://192.168.2.51/api/v1/userstories/(?P<resource_id>\\d+)/voters",
        "projects/(?P<resource_id>\\d+)/fans": "http://192.168.2.51/api/v1/projects/(?P<resource_id>\\d+)/fans",
        "tasks/(?P<resource_id>\\d+)/voters": "http://192.168.2.51/api/v1/tasks/(?P<resource_id>\\d+)/voters",
        "github-hook": "http://192.168.2.51/api/v1/github-hook",
        "wiki": "http://192.168.2.51/api/v1/wiki",
        "issues/attachments": "http://192.168.2.51/api/v1/issues/attachments",
        "notify-policies": "http://192.168.2.51/api/v1/notify-policies",
        "projects": "http://192.168.2.51/api/v1/projects",
        "issues": "http://192.168.2.51/api/v1/issues",
        "issues/custom-attributes-values": "http://192.168.2.51/api/v1/issues/custom-attributes-values",
        "locales": "http://192.168.2.51/api/v1/locales",
        "history/userstory": "http://192.168.2.51/api/v1/history/userstory",
        "history/task": "http://192.168.2.51/api/v1/history/task",
        "project-templates": "http://192.168.2.51/api/v1/project-templates",
        "webhooks": "http://192.168.2.51/api/v1/webhooks",
        "priorities": "http://192.168.2.51/api/v1/priorities",
        "issue-types": "http://192.168.2.51/api/v1/issue-types",
        "user-storage": "http://192.168.2.51/api/v1/user-storage",
        "roles": "http://192.168.2.51/api/v1/roles",
        "tasks": "http://192.168.2.51/api/v1/tasks",
        "tasks/custom-attributes-values": "http://192.168.2.51/api/v1/tasks/custom-attributes-values",
        "invitations": "http://192.168.2.51/api/v1/invitations",
        "search": "http://192.168.2.51/api/v1/search",
        "history/issue": "http://192.168.2.51/api/v1/history/issue",
        "task-custom-attributes": "http://192.168.2.51/api/v1/task-custom-attributes",
        "wiki/attachments": "http://192.168.2.51/api/v1/wiki/attachments",
        "tasks/attachments": "http://192.168.2.51/api/v1/tasks/attachments",
        "milestones/(?P<resource_id>\\d+)/watchers": "http://192.168.2.51/api/v1/milestones/(?P<resource_id>\\d+)/watchers",
        "timeline/user": "http://192.168.2.51/api/v1/timeline/user",
        "auth": "http://192.168.2.51/api/v1/auth",
        "wiki-links": "http://192.168.2.51/api/v1/wiki-links",
        "userstories": "http://192.168.2.51/api/v1/userstories",
        "userstories/(?P<resource_id>\\d+)/watchers": "http://192.168.2.51/api/v1/userstories/(?P<resource_id>\\d+)/watchers",
        "issue-statuses": "http://192.168.2.51/api/v1/issue-statuses",
        "memberships": "http://192.168.2.51/api/v1/memberships",
        "wiki/(?P<resource_id>\\d+)/watchers": "http://192.168.2.51/api/v1/wiki/(?P<resource_id>\\d+)/watchers",
        "projects/(?P<resource_id>\\d+)/watchers": "http://192.168.2.51/api/v1/projects/(?P<resource_id>\\d+)/watchers",
        "tasks/(?P<resource_id>\\d+)/watchers": "http://192.168.2.51/api/v1/tasks/(?P<resource_id>\\d+)/watchers",
        "severities": "http://192.168.2.51/api/v1/severities",
        "issues/(?P<resource_id>\\d+)/watchers": "http://192.168.2.51/api/v1/issues/(?P<resource_id>\\d+)/watchers",
        "task-statuses": "http://192.168.2.51/api/v1/task-statuses",
        "bitbucket-hook": "http://192.168.2.51/api/v1/bitbucket-hook",
        "userstory-statuses": "http://192.168.2.51/api/v1/userstory-statuses",
        "userstories/custom-attributes-values": "http://192.168.2.51/api/v1/userstories/custom-attributes-values",
        "userstories/attachments": "http://192.168.2.51/api/v1/userstories/attachments",
        "userstory-custom-attributes": "http://192.168.2.51/api/v1/userstory-custom-attributes",
        "users": "http://192.168.2.51/api/v1/users",
        "importer": "http://192.168.2.51/api/v1/importer",
        "application-tokens": "http://192.168.2.51/api/v1/application-tokens",
        "timeline/profile": "http://192.168.2.51/api/v1/timeline/profile"
}

```

**Comment by ddonindia** [comment]
@superalex can you please repopen this issue ?

**Comment by superalex** [comment]
And what's the output for http://192.168.2.51/api/v1/projects?discover_mode=true&order_by=-total_fans_last_week from your browser?

**Comment by ddonindia** [comment]
@superalex I got following error in taiga-back

```
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit
Subject: [Django] ERROR (EXTERNAL IP): Internal Server Error: /api/v1/projects
From: no-reply@example.com
To: example@example.com
Date: Mon, 29 Feb 2016 10:55:15 -0000
Message-ID: <20160229105515.15732.29988@myrpi>

Internal Server Error: /api/v1/projects
Traceback (most recent call last):
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/ubuntu/src/taiga-back/taiga/base/response.py", line 98, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "/home/ubuntu/src/taiga-back/taiga/base/api/renderers.py", line 632, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/ubuntu/src/taiga-back/taiga/base/api/renderers.py", line 609, in get_context
    "post_form": self.get_rendered_html_form(view, "POST", request),
  File "/home/ubuntu/src/taiga-back/taiga/base/api/renderers.py", line 492, in get_rendered_html_form
    return form_renderer.render(data, self.accepted_media_type, self.renderer_context)
  File "/home/ubuntu/src/taiga-back/taiga/base/api/renderers.py", line 390, in render
    return template.render(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/defaulttags.py", line 224, in render
    nodelist.append(node.render(context))
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 959, in render
    output = self.filter_expression.resolve(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 648, in resolve
    obj = self.var.resolve(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 789, in resolve
    value = self._resolve_lookup(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current()
  File "/home/ubuntu/src/taiga-back/taiga/base/api/fields.py", line 197, in widget_html
    return self.widget.render(self._name, self._value)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/forms/widgets.py", line 513, in render
    options = self.render_options(choices, [value])
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/forms/widgets.py", line 539, in render_options
    for option_value, option_label in chain(self.choices, choices):
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/forms/models.py", line 1095, in __iter__
    method = 'all' if self.queryset._prefetch_related_lookups else 'iterator'
AttributeError: 'Manager' object has no attribute '_prefetch_related_lookups'

path:/api/v1/projects,                                                                                                                                                                                                              [99/1021]
GET:<QueryDict: {'discover_mode': ['true'], 'order_by': ['-total_fans_last_week']}>,
POST:<QueryDict: {}>,
COOKIES:{'csrftoken': 'mLTcVP7mEeVU73w9ZNgXjuYZ2OhQSzIr'},
META:{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': 'text/plain',
 'CSRF_COOKIE_USED': True,
 'DERBY_HOME': '/usr/lib/jvm/java-8-oracle/db',
 'DJANGO_SETTINGS_MODULE': 'settings',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'GOPATH': '/home/ubuntu/gopath',
 'HOME': '/home/ubuntu',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-in;q=1.0',
 'HTTP_CONNECTION': 'close',
 'HTTP_COOKIE': 'csrftoken=mLTcVP7mEeVU73w9ZNgXjuYZ2OhQSzIr',
 'HTTP_HOST': '192.168.2.51',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux) AppleWebKit/538.15 (KHTML, '
                    'like Gecko) Chrome/46.0.2490.86 Safari/538.15 Midori/0.5',
 'HTTP_X_FORWARDED_FOR': '192.168.2.51',
 'HTTP_X_FORWARDED_PROTO': 'http',
 'HTTP_X_REAL_IP': '192.168.2.51',
 'HTTP_X_SCHEME': 'http',
 'J2REDIR': '/usr/lib/jvm/java-8-oracle/jre',
 'J2SDKDIR': '/usr/lib/jvm/java-8-oracle',
 'JAVA_HOME': '/usr/lib/jvm/java-8-oracle',
 'LANG': 'en_IN',
 'LANGUAGE': 'en_IN:en',
 'LD_LIBRARY_PATH': ':/usr/local/lib:/usr/local/lib',
 'LESSCLOSE': '/usr/bin/lesspipe %s %s',
 'LESSOPEN': '| /usr/bin/lesspipe %s',
 'LESS_TERMCAP_mb': '\x1b[31m',
 'LESS_TERMCAP_md': '\x1b[91m',
 'LESS_TERMCAP_me': '\x1b[m\x0f',
 'LESS_TERMCAP_se': '\x1b[m\x0f',
 'LESS_TERMCAP_so': '\x1b[35m',
 'LESS_TERMCAP_ue': '\x1b[m\x0f',
 'LESS_TERMCAP_us': '\x1b[32m',
 'LOGNAME': 'ubuntu',
 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=0
1;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31
:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;
35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.
mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*
.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;3
6:*.xspf=00;36:',
 'LS_OPTS': '--color=auto',
 'MAIL': '/var/mail/ubuntu',
 'OLDPWD': '/home/ubuntu/src',
 'PAGER': 'less',
 'PATH': '/home/ubuntu/src/taiga-back/taiga/bin:/opt/node-v4.3.1-linux-armv7l/bin:/home/ubuntu/.gem/ruby/2.1.0/bin:/home/ubuntu/gopath:/home/ubuntu/gopath/bin:/home/ubuntu/.gem/ruby/2.1.0/bin:/opt/bin:/opt/node-v4.3.1-linux-armv7l/bin:/h
ome/ubuntu/.gem/ruby/2.1.0/bin:/home/ubuntu/gopath:/home/ubuntu/gopath/bin:/home/ubuntu/.gem/ruby/2.1.0/bin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:
/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin',
 'PATH_INFO': '/api/v1/projects',
 'PS1': '(taiga)${debian_chroot:+($debian_chroot)}\\u@\\h:\\w\\$ ',
 'PWD': '/home/ubuntu/src/taiga-back',
 'QUERY_STRING': 'discover_mode=true&order_by=-total_fans_last_week',
 'REMOTE_ADDR': '192.168.2.51',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'GET',
 'RUN_MAIN': 'true',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '192.168.2.51',
 'SERVER_PORT': '8001',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'SERVER_PROTOCOL': 'HTTP/1.0',                                                                                                                                             
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'SHELL': '/bin/bash',
 'SHLVL': '2',
 'SSH_CLIENT': '192.168.2.3 49907 22',
 'SSH_CONNECTION': '199.43.186.25 33674 192.168.2.51 22',
 'SSH_TTY': '/dev/pts/1',
 'TERM': 'screen-256color',
 'TMUX': '/tmp/tmux-1000/default,23448,0',
 'TMUX_PANE': '%1',
 'TMUX_VERSION_MAJOR': '2',
 'TMUX_VERSION_MINOR': '2',
 'TZ': 'UTC',
 'USER': 'ubuntu',
 'VIRTUALENVWRAPPER_SCRIPT': '/usr/share/virtualenvwrapper/virtualenvwrapper.sh',
 'VIRTUAL_ENV': '/home/ubuntu/src/taiga-back/taiga',
 'XDG_RUNTIME_DIR': '/run/user/1000',
 'XDG_SESSION_ID': 'c5',
 '_': '/home/ubuntu/src/taiga-back/taiga/bin/python',
 '_VIRTUALENVWRAPPER_API': ' mkvirtualenv rmvirtualenv lsvirtualenv '
                           'showvirtualenv workon add2virtualenv '
                           'cdsitepackages cdvirtualenv lssitepackages '
                           'toggleglobalsitepackages cpvirtualenv '
                           'setvirtualenvproject mkproject cdproject '
                           'mktmpenv mkvirtualenv rmvirtualenv lsvirtualenv '
                           'showvirtualenv workon add2virtualenv '
                           'cdsitepackages cdvirtualenv lssitepackages '
                           'toggleglobalsitepackages cpvirtualenv '
                           'setvirtualenvproject mkproject cdproject '
                           'mktmpenv mkvirtualenv rmvirtualenv lsvirtualenv '
                           'showvirtualenv workon add2virtualenv '
                           'cdsitepackages cdvirtualenv lssitepackages '
                           'toggleglobalsitepackages cpvirtualenv '
                           'setvirtualenvproject mkproject cdproject '
                           'mktmpenv mkvirtualenv rmvirtualenv lsvirtualenv '
                           'showvirtualenv workon add2virtualenv '
                           'cdsitepackages cdvirtualenv lssitepackages '
                           'toggleglobalsitepackages cpvirtualenv '
                           'setvirtualenvproject mkproject cdproject mktmpenv',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=7>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
-------------------------------------------------------------------------------
ERROR:2016-02-29 10:55:15,195: Internal Server Error: /api/v1/projects
Traceback (most recent call last):
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/ubuntu/src/taiga-back/taiga/base/response.py", line 98, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "/home/ubuntu/src/taiga-back/taiga/base/api/renderers.py", line 632, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/ubuntu/src/taiga-back/taiga/base/api/renderers.py", line 609, in get_context
    "post_form": self.get_rendered_html_form(view, "POST", request),
  File "/home/ubuntu/src/taiga-back/taiga/base/api/renderers.py", line 492, in get_rendered_html_form
    return form_renderer.render(data, self.accepted_media_type, self.renderer_context)
  File "/home/ubuntu/src/taiga-back/taiga/base/api/renderers.py", line 390, in render
    return template.render(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 210, in render
                           'mktmpenv mkvirtualenv rmvirtualenv lsvirtualenv '                                                                                                                                                        
                           'showvirtualenv workon add2virtualenv '
                           'cdsitepackages cdvirtualenv lssitepackages '
                           'toggleglobalsitepackages cpvirtualenv '
                           'setvirtualenvproject mkproject cdproject mktmpenv',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=7>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
-------------------------------------------------------------------------------
ERROR:2016-02-29 10:55:15,195: Internal Server Error: /api/v1/projects
Traceback (most recent call last):
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/ubuntu/src/taiga-back/taiga/base/response.py", line 98, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "/home/ubuntu/src/taiga-back/taiga/base/api/renderers.py", line 632, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/ubuntu/src/taiga-back/taiga/base/api/renderers.py", line 609, in get_context
    "post_form": self.get_rendered_html_form(view, "POST", request),
  File "/home/ubuntu/src/taiga-back/taiga/base/api/renderers.py", line 492, in get_rendered_html_form
    return form_renderer.render(data, self.accepted_media_type, self.renderer_context)
  File "/home/ubuntu/src/taiga-back/taiga/base/api/renderers.py", line 390, in render
    return template.render(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/defaulttags.py", line 224, in render
    nodelist.append(node.render(context))
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 959, in render
    output = self.filter_expression.resolve(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 648, in resolve
    obj = self.var.resolve(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 789, in resolve
    value = self._resolve_lookup(context)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current()
  File "/home/ubuntu/src/taiga-back/taiga/base/api/fields.py", line 197, in widget_html
    return self.widget.render(self._name, self._value)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/forms/widgets.py", line 513, in render
    options = self.render_options(choices, [value])
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/forms/widgets.py", line 539, in render_options
    for option_value, option_label in chain(self.choices, choices):
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/forms/models.py", line 1095, in __iter__
    method = 'all' if self.queryset._prefetch_related_lookups else 'iterator'
AttributeError: 'Manager' object has no attribute '_prefetch_related_lookups'

```

**Comment by superalex** [comment]
what version of django are you using?

`pip show django`

**Comment by ddonindia** [comment]
In my virtualenv I am using Django 1.8.6 
ubuntu@myrpi:~/src/taiga-back$ source taiga/bin/activate
(taiga)ubuntu@myrpi:~/src/taiga-back$ pip show django
---
Name: Django
**Version: 1.8.6**
Location: /home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages
Requires:
(taiga)ubuntu@myrpi:~/src/taiga-back$

```

**Comment by superalex** [comment]
The _prefetch_related_lookups seems related to this: https://github.com/taigaio/taiga-back/issues/602

Could you try reinstalling the virtualenv?

**Comment by ddonindia** [comment]
After upgrading virtualenv (I deleted venv folder and did fresh install of venv ) I am getting following error in taiga-back 

```
Trying import local.py settings...
Traceback (most recent call last):
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/apps/config.py", line 114, in create
    cls = getattr(mod, cls_name)
AttributeError: 'module' object has no attribute 'base'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/site-packages/django/apps/config.py", line 119, in create
    import_module(entry)
  File "/home/ubuntu/src/taiga-back/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'taiga.base'

```

**Comment by ddonindia** [comment]
Trying with fresh repo clone.

**Comment by ddonindia** [comment]
Not getting any 505 error on http://192.168.2.51/api/v1/projects?discover_mode=true&order_by=-total_fans_last_week but still same issue with signup link :(

**Comment by ddonindia** [comment]
As a workaround I am able to add new use  in add member link on Project page.
Thaks @superalex  for your help and support.

**Comment by superalex** [comment]
You are welcome! ;)
