### ISSUE TITLE
Taiga Scripts Installs Smoothly; fails on connect

### ISSUE THREAD

**Issue by Rob117** [taigaio/taiga-front#873]
Firstly, Taiga seems awesome, and I'm very excited to try to use it.

I was running an AWS EC2 instance with rocketchat on it. I ssh into it and installed and ran Taiga via Tiaga scripts. No problems. I went to my site (via my home computer, not inside the aws instance). The nginx settings for rocketchat were completely overridden. Still, no problem. 

Taiga redirects to an error page and tells me something about oompa loompas. I check the console, 5 error messages consisting of calls to the API through localhost.

Search the bejeezus out of the problem. No clear way to fix this. Poured through the existing docs, tried every fix I read about, nothing. I was surprised because taiga scripts made this look so easy. I would use vagrant, but that really isn't an option on AWS because no virtualbox.

Okay, no problem. Remove the taiga folders under ~, stop the circusctl process, delete the nginx file.

My old Rocketchat instance absolutely will not boot. Now I feel like I've lost out for trying.

I also installed a completely clean install on a different AWS VM (and double-checked that all the ports that I needed were opened, etc).

Same problem.

Error messages that appeared when setup-server.sh ran:

touch: cannot touch ‘/home/ubuntu/.setup/postgresql’: No such file or directory
touch: cannot touch ‘/home/ubuntu/.setup/buildessential’: No such file or directory

mv: cannot move ‘/tmp/conf.json’ to ‘dist/js/’: Not a directory

Could not find a tag or branch 'dbb8d7375066859f897604132bd437832d2014ea', assuming commit.

(WALL OF TEXT)

`Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/ubuntu/taiga-back/taiga/__init__.py", line 18, in <module>
    from . import celery
  File "/home/ubuntu/taiga-back/taiga/celery.py", line 20, in <module>
    from celery import Celery
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/five.py", line 306, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/app/__init__.py", line 14, in <module>
    from celery import _state
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/_state.py", line 20, in <module>
    from celery.utils.threads import LocalStack
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/utils/__init__.py", line 27, in <module>
    from celery.exceptions import CPendingDeprecationWarning, CDeprecationWarning
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/exceptions.py", line 15, in <module>
    from billiard.exceptions import (  # noqa
ImportError: No module named 'billiard'
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/ubuntu/taiga-back/taiga/__init__.py", line 18, in <module>
    from . import celery
  File "/home/ubuntu/taiga-back/taiga/celery.py", line 20, in <module>
    from celery import Celery
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/five.py", line 306, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/app/__init__.py", line 14, in <module>
    from celery import _state
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/_state.py", line 20, in <module>
    from celery.utils.threads import LocalStack
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/utils/__init__.py", line 27, in <module>
    from celery.exceptions import CPendingDeprecationWarning, CDeprecationWarning
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/exceptions.py", line 15, in <module>
    from billiard.exceptions import (  # noqa
ImportError: No module named 'billiard'
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/ubuntu/taiga-back/taiga/__init__.py", line 18, in <module>
    from . import celery
  File "/home/ubuntu/taiga-back/taiga/celery.py", line 20, in <module>
    from celery import Celery
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/five.py", line 306, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/app/__init__.py", line 14, in <module>
    from celery import _state
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/_state.py", line 20, in <module>
    from celery.utils.threads import LocalStack
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/utils/__init__.py", line 27, in <module>
    from celery.exceptions import CPendingDeprecationWarning, CDeprecationWarning
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/exceptions.py", line 15, in <module>
    from billiard.exceptions import (  # noqa
ImportError: No module named 'billiard'
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/ubuntu/taiga-back/taiga/__init__.py", line 18, in <module>
    from . import celery
  File "/home/ubuntu/taiga-back/taiga/celery.py", line 20, in <module>
    from celery import Celery
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/five.py", line 306, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/app/__init__.py", line 14, in <module>
    from celery import _state
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/_state.py", line 20, in <module>
    from celery.utils.threads import LocalStack
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/utils/__init__.py", line 27, in <module>
    from celery.exceptions import CPendingDeprecationWarning, CDeprecationWarning
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/exceptions.py", line 15, in <module>
    from billiard.exceptions import (  # noqa
ImportError: No module named 'billiard'
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/ubuntu/taiga-back/taiga/__init__.py", line 18, in <module>
    from . import celery
  File "/home/ubuntu/taiga-back/taiga/celery.py", line 20, in <module>
    from celery import Celery
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/five.py", line 306, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/app/__init__.py", line 14, in <module>
    from celery import _state
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/_state.py", line 20, in <module>
    from celery.utils.threads import LocalStack
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/utils/__init__.py", line 27, in <module>
    from celery.exceptions import CPendingDeprecationWarning, CDeprecationWarning
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/exceptions.py", line 15, in <module>
    from billiard.exceptions import (  # noqa
ImportError: No module named 'billiard'
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/ubuntu/taiga-back/taiga/__init__.py", line 18, in <module>
    from . import celery
  File "/home/ubuntu/taiga-back/taiga/celery.py", line 20, in <module>
    from celery import Celery
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/five.py", line 306, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/app/__init__.py", line 14, in <module>
    from celery import _state
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/_state.py", line 20, in <module>
    from celery.utils.threads import LocalStack
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/utils/__init__.py", line 27, in <module>
    from celery.exceptions import CPendingDeprecationWarning, CDeprecationWarning
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/exceptions.py", line 15, in <module>
    from billiard.exceptions import (  # noqa
ImportError: No module named 'billiard'
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/ubuntu/taiga-back/taiga/__init__.py", line 18, in <module>
    from . import celery
  File "/home/ubuntu/taiga-back/taiga/celery.py", line 20, in <module>
    from celery import Celery
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/five.py", line 306, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/app/__init__.py", line 14, in <module>
    from celery import _state
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/_state.py", line 20, in <module>
    from celery.utils.threads import LocalStack
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/utils/__init__.py", line 27, in <module>
    from celery.exceptions import CPendingDeprecationWarning, CDeprecationWarning
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/exceptions.py", line 15, in <module>
    from billiard.exceptions import (  # noqa
ImportError: No module named 'billiard'
`
--------------------------------------------------------------------------------------------------
touch: cannot touch ‘/home/ubuntu/.setup/circus’: No such file or directory

=================================================================
From the website:

site URL: 

greystonegames.com

Js console error:

Failed to load resource: net::ERR_CONNECTION_REFUSED
http://localhost:8000/api/v1/projects?order_by=-total_fans_last_week Failed to load resource: net::ERR_CONNECTION_REFUSED
http://localhost:8000/api/v1/projects?order_by=-total_activity_last_week Failed to load resource: net::ERR_CONNECTION_REFUSED
http://localhost:8000/api/v1/projects?is_featured=true Failed to load resource: net::ERR_CONNECTION_REFUSED
chrome-extension://jipdnfibhldikgcjhfnomkfpcebammhp/jquery-1.7.1.min.js:2 Uncaught TypeError: Cannot read property 'opacity' of undefined

**Comment by superalex** [comment]
Hello @Rob117 

I'm sorry your installation process went wrong, taiga-script is designed to be used on a clean ubuntu 14.04 machine (https://taigaio.github.io/taiga-doc/dist/setup-alternatives.html#_requirements) I think we should make it clearer in case you are using it on a machine with more stuff installed. We keep the doc in another github repo (https://github.com/taigaio/taiga-doc) so if you find anything wrong on that we will really appreciate if you send us a pull request improving it.

It seems you python dependencies weren't correctly installed, actually Taiga have this requirements (https://taigaio.github.io/taiga-doc/dist/#requirements), if using a AWS instance you should check you have enough RAM.

Regards!,
