### ISSUE TITLE
unable to give project member admin rights

### ISSUE THREAD

**Issue by ddonindia** [taigaio/taiga-front#901]
Hi,

I have local project on my self hosted Taiga env. I have few users added in it.
Now I want to make one of them admin on "Manage members" page ( I am login in as Admin )
When I click on admin Yes/no button I get green pop saying changes done. 
But when I come back to Manage members page  again admin setting for that user is still No.

Is it a known issue?

**Comment by superalex** [comment]
Hello @ddonindia 

I've just tested it in our SaaS and in my development instance and it seems to work ok. Did you check your javascript console/logs folder to see if there is any error?

Regards,

**Comment by ddonindia** [comment]
When I click on yes/no button I got is_admin = false in response. 
![error](https://cloud.githubusercontent.com/assets/16450468/13458968/85e374aa-e096-11e5-8e0d-
3aec7171f3f2.png)

**Comment by superalex** [comment]
It should but...it seems you are using the master branch?, why not using the stable one?

**Comment by ddonindia** [comment]
Master branch for taiga-front or taiga-back ?
I am using taiga-front-dist and taiga-back master.

**Comment by superalex** [comment]
You should be using stable branches in both sides...

**Comment by ddonindia** [comment]
ok. I have one project created I will I loose any data if I switch branch ?

**Comment by superalex** [comment]
You shouldn't but you could have a situation where the database doesn't fit the models after moving to master you should execute something like:

```
python manage.py makemigrations
python manage.py migrate
```

**Comment by ddonindia** [comment]
@superalex  thanks alot. I will move to stable branch and test it.

**Comment by superalex** [comment]
Great!, let us know if it works.

Regards!,

**Comment by ddonindia** [comment]
I am getting following exception with stable branch:
```


ERROR:2016-03-03 08:34:34,759: Internal Server Error: /api/v1/projects
Traceback (most recent call last):
  File "/home/ubuntu/src/taiga-back/venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column projects_membership.is_owner does not exist
LINE 1: ...p"."project_id", "projects_membership"."role_id", "projects_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/src/taiga-back/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/src/taiga-back/taiga/base/api/viewsets.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/src/taiga-back/venv/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/src/taiga-back/taiga/base/api/views.py", line 444, in dispatch
    response = self.handle_exception(exc)
  File "/home/ubuntu/src/taiga-back/taiga/base/api/views.py", line 441, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ubuntu/src/taiga-back/taiga/base/api/mixins.py", line 139, in list
    return response.Ok(serializer.data)
  File "/home/ubuntu/src/taiga-back/taiga/base/api/serializers.py", line 613, in data
    self._data = [self.to_native(item) for item in obj]
  File "/home/ubuntu/src/taiga-back/taiga/base/api/serializers.py", line 613, in <listcomp>
    self._data = [self.to_native(item) for item in obj]
  File "/home/ubuntu/src/taiga-back/taiga/base/api/serializers.py", line 396, in to_native
    value = field.field_to_native(obj, field_name)
  File "/home/ubuntu/src/taiga-back/taiga/base/api/fields.py", line 1082, in field_to_native
    value = getattr(self.parent, self.method_name)(obj)
  File "/home/ubuntu/src/taiga-back/taiga/projects/serializers.py", line 266, in get_my_permissions
    return get_user_project_permissions(self.context["request"].user, obj)
  File "/home/ubuntu/src/taiga-back/taiga/permissions/service.py", line 80, in get_user_project_permissions
    membership = _get_user_project_membership(user, project)
  File "/home/ubuntu/src/taiga-back/taiga/permissions/service.py", line 28, in _get_user_project_membership
    return user.cached_membership_for_project(project)
  File "/home/ubuntu/src/taiga-back/taiga/users/models.py", line 159, in cached_membership_for_project
    self._fill_cached_memberships()
  File "/home/ubuntu/src/taiga-back/taiga/users/models.py", line 147, in _fill_cached_memberships
    for membership in qs.all():
  File "/home/ubuntu/src/taiga-back/venv/lib/python3.4/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/home/ubuntu/src/taiga-back/venv/lib/python3.4/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/ubuntu/src/taiga-back/venv/lib/python3.4/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/ubuntu/src/taiga-back/venv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/src/taiga-back/venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/src/taiga-back/venv/lib/python3.4/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ubuntu/src/taiga-back/venv/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/src/taiga-back/venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column projects_membership.is_owner does not exist
LINE 1: ...p"."project_id", "projects_membership"."role_id", "projects_...
 
```

**Comment by bameda** [comment]
Your db doesn't have some columns... 

what's the output of the makemigration command?...

You need some migrations

**Comment by bameda** [comment]
Try with `./manage.py makemigrations -v 3 ` and `./manage.py makemigrations -v 3 --merge   projects`

**Comment by ddonindia** [comment]
(venv)~/src/taiga-back$ ./manage.py makemigrations -v 3
Trying import local.py settings...
**No changes detected**
(venv)~/src/taiga-back$ ./manage.py makemigrations -v 3 --merge projects
Trying import local.py settings...
**No conflicts detected to merge.**

**Comment by ddonindia** [comment]
Still same error :(

**Comment by bameda** [comment]
Ok, so you have two alternatives:

- revert all migrations manually, checking the differences (new migration files added) between master and stable branch.
- regenerate the database.

@superalex do you have anything more?

**Comment by superalex** [comment]
No more ideas @bameda

**Comment by ddonindia** [comment]
Ok I will try to regenerate db and import my projects in it.
Thanks @superalex and @bameda.

**Comment by bameda** [comment]
You are welcome
